/*
 * This file is generated by jOOQ.
*/
package fi.redgrenade.summarizer.db.tables;


import fi.redgrenade.summarizer.db.Keys;
import fi.redgrenade.summarizer.db.Public;
import fi.redgrenade.summarizer.db.tables.records.KeyWordRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KeyWord extends TableImpl<KeyWordRecord> {

    private static final long serialVersionUID = 137945063;

    /**
     * The reference instance of <code>public.key_word</code>
     */
    public static final KeyWord KEY_WORD = new KeyWord();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KeyWordRecord> getRecordType() {
        return KeyWordRecord.class;
    }

    /**
     * The column <code>public.key_word.id</code>.
     */
    public final TableField<KeyWordRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('key_word_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.key_word.word</code>.
     */
    public final TableField<KeyWordRecord, String> WORD = createField("word", org.jooq.impl.SQLDataType.VARCHAR.length(511).nullable(false), this, "");

    /**
     * Create a <code>public.key_word</code> table reference
     */
    public KeyWord() {
        this("key_word", null);
    }

    /**
     * Create an aliased <code>public.key_word</code> table reference
     */
    public KeyWord(String alias) {
        this(alias, KEY_WORD);
    }

    private KeyWord(String alias, Table<KeyWordRecord> aliased) {
        this(alias, aliased, null);
    }

    private KeyWord(String alias, Table<KeyWordRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<KeyWordRecord, Long> getIdentity() {
        return Keys.IDENTITY_KEY_WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<KeyWordRecord> getPrimaryKey() {
        return Keys.PK_KEY_WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<KeyWordRecord>> getKeys() {
        return Arrays.<UniqueKey<KeyWordRecord>>asList(Keys.PK_KEY_WORD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KeyWord as(String alias) {
        return new KeyWord(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public KeyWord rename(String name) {
        return new KeyWord(name, null);
    }
}
