/*
 * This file is generated by jOOQ.
*/
package fi.redgrenade.summarizer.db;


import fi.redgrenade.summarizer.db.tables.Article;
import fi.redgrenade.summarizer.db.tables.ArticleKeyWord;
import fi.redgrenade.summarizer.db.tables.Databasechangelog;
import fi.redgrenade.summarizer.db.tables.Databasechangeloglock;
import fi.redgrenade.summarizer.db.tables.KeyWord;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -843185113;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.article</code>.
     */
    public final Article ARTICLE = fi.redgrenade.summarizer.db.tables.Article.ARTICLE;

    /**
     * The table <code>public.article_key_word</code>.
     */
    public final ArticleKeyWord ARTICLE_KEY_WORD = fi.redgrenade.summarizer.db.tables.ArticleKeyWord.ARTICLE_KEY_WORD;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = fi.redgrenade.summarizer.db.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = fi.redgrenade.summarizer.db.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.key_word</code>.
     */
    public final KeyWord KEY_WORD = fi.redgrenade.summarizer.db.tables.KeyWord.KEY_WORD;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ARTICLE_ID_SEQ,
            Sequences.ARTICLE_KEY_WORD_ARTICLE_ID_SEQ,
            Sequences.ARTICLE_KEY_WORD_KEY_WORD_ID_SEQ,
            Sequences.KEY_WORD_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Article.ARTICLE,
            ArticleKeyWord.ARTICLE_KEY_WORD,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            KeyWord.KEY_WORD);
    }
}
