/*
 * This file is generated by jOOQ.
*/
package fi.redgrenade.summarizer.db;


import fi.redgrenade.summarizer.db.tables.Databasechangelog;
import fi.redgrenade.summarizer.db.tables.Databasechangeloglock;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = fi.redgrenade.summarizer.db.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = fi.redgrenade.summarizer.db.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;
}
