/*
 * This file is generated by jOOQ.
*/
package fi.redgrenade.summarizer.db;


import fi.redgrenade.summarizer.db.tables.Article;
import fi.redgrenade.summarizer.db.tables.ArticleKeyWord;
import fi.redgrenade.summarizer.db.tables.Databasechangelog;
import fi.redgrenade.summarizer.db.tables.Databasechangeloglock;
import fi.redgrenade.summarizer.db.tables.KeyWord;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.article</code>.
     */
    public static final Article ARTICLE = fi.redgrenade.summarizer.db.tables.Article.ARTICLE;

    /**
     * The table <code>public.article_key_word</code>.
     */
    public static final ArticleKeyWord ARTICLE_KEY_WORD = fi.redgrenade.summarizer.db.tables.ArticleKeyWord.ARTICLE_KEY_WORD;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = fi.redgrenade.summarizer.db.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = fi.redgrenade.summarizer.db.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.key_word</code>.
     */
    public static final KeyWord KEY_WORD = fi.redgrenade.summarizer.db.tables.KeyWord.KEY_WORD;
}
