/*
 * This file is generated by jOOQ.
*/
package fi.redgrenade.summarizer.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleKeyWord implements Serializable {

    private static final long serialVersionUID = 356604534;

    private Long articleId;
    private Long keyWordId;

    public ArticleKeyWord() {}

    public ArticleKeyWord(ArticleKeyWord value) {
        this.articleId = value.articleId;
        this.keyWordId = value.keyWordId;
    }

    public ArticleKeyWord(
        Long articleId,
        Long keyWordId
    ) {
        this.articleId = articleId;
        this.keyWordId = keyWordId;
    }

    public Long getArticleId() {
        return this.articleId;
    }

    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    public Long getKeyWordId() {
        return this.keyWordId;
    }

    public void setKeyWordId(Long keyWordId) {
        this.keyWordId = keyWordId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ArticleKeyWord (");

        sb.append(articleId);
        sb.append(", ").append(keyWordId);

        sb.append(")");
        return sb.toString();
    }
}
