/*
 * This file is generated by jOOQ.
*/
package fi.redgrenade.summarizer.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KeyWord implements Serializable {

    private static final long serialVersionUID = -1830979332;

    private Long   id;
    private String word;

    public KeyWord() {}

    public KeyWord(KeyWord value) {
        this.id = value.id;
        this.word = value.word;
    }

    public KeyWord(
        Long   id,
        String word
    ) {
        this.id = id;
        this.word = word;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWord() {
        return this.word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("KeyWord (");

        sb.append(id);
        sb.append(", ").append(word);

        sb.append(")");
        return sb.toString();
    }
}
