/*
 * This file is generated by jOOQ.
*/
package fi.redgrenade.summarizer.db.tables.records;


import fi.redgrenade.summarizer.db.tables.Article;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleRecord extends UpdatableRecordImpl<ArticleRecord> implements Record9<Long, String, String, String, Timestamp, Timestamp, String, String, String> {

    private static final long serialVersionUID = 1389523465;

    /**
     * Setter for <code>public.article.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.article.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.article.content</code>.
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.article.content</code>.
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.article.header</code>.
     */
    public void setHeader(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.article.header</code>.
     */
    public String getHeader() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.article.summary</code>.
     */
    public void setSummary(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.article.summary</code>.
     */
    public String getSummary() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.article.timestamp</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.article.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.article.rowcreatetime</code>.
     */
    public void setRowcreatetime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.article.rowcreatetime</code>.
     */
    public Timestamp getRowcreatetime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.article.category</code>.
     */
    public void setCategory(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.article.category</code>.
     */
    public String getCategory() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.article.imageurl</code>.
     */
    public void setImageurl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.article.imageurl</code>.
     */
    public String getImageurl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.article.emotion</code>.
     */
    public void setEmotion(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.article.emotion</code>.
     */
    public String getEmotion() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, Timestamp, Timestamp, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, Timestamp, Timestamp, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Article.ARTICLE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Article.ARTICLE.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Article.ARTICLE.HEADER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Article.ARTICLE.SUMMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Article.ARTICLE.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Article.ARTICLE.ROWCREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Article.ARTICLE.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Article.ARTICLE.IMAGEURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Article.ARTICLE.EMOTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getHeader();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSummary();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getRowcreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getImageurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getEmotion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value2(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value3(String value) {
        setHeader(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value4(String value) {
        setSummary(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value5(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value6(Timestamp value) {
        setRowcreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value7(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value8(String value) {
        setImageurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord value9(String value) {
        setEmotion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleRecord values(Long value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleRecord
     */
    public ArticleRecord() {
        super(Article.ARTICLE);
    }

    /**
     * Create a detached, initialised ArticleRecord
     */
    public ArticleRecord(Long id, String content, String header, String summary, Timestamp timestamp, Timestamp rowcreatetime, String category, String imageurl, String emotion) {
        super(Article.ARTICLE);

        set(0, id);
        set(1, content);
        set(2, header);
        set(3, summary);
        set(4, timestamp);
        set(5, rowcreatetime);
        set(6, category);
        set(7, imageurl);
        set(8, emotion);
    }
}
