/*
 * This file is generated by jOOQ.
*/
package fi.redgrenade.summarizer.db.tables.records;


import fi.redgrenade.summarizer.db.tables.ArticleKeyWord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleKeyWordRecord extends UpdatableRecordImpl<ArticleKeyWordRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -1514138360;

    /**
     * Setter for <code>public.article_key_word.article_id</code>.
     */
    public void setArticleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.article_key_word.article_id</code>.
     */
    public Long getArticleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.article_key_word.key_word_id</code>.
     */
    public void setKeyWordId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.article_key_word.key_word_id</code>.
     */
    public Long getKeyWordId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ArticleKeyWord.ARTICLE_KEY_WORD.ARTICLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ArticleKeyWord.ARTICLE_KEY_WORD.KEY_WORD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getArticleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getKeyWordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleKeyWordRecord value1(Long value) {
        setArticleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleKeyWordRecord value2(Long value) {
        setKeyWordId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ArticleKeyWordRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleKeyWordRecord
     */
    public ArticleKeyWordRecord() {
        super(ArticleKeyWord.ARTICLE_KEY_WORD);
    }

    /**
     * Create a detached, initialised ArticleKeyWordRecord
     */
    public ArticleKeyWordRecord(Long articleId, Long keyWordId) {
        super(ArticleKeyWord.ARTICLE_KEY_WORD);

        set(0, articleId);
        set(1, keyWordId);
    }
}
