/*
 * This file is generated by jOOQ.
*/
package fi.redgrenade.summarizer.db.tables.daos;


import fi.redgrenade.summarizer.db.tables.Article;
import fi.redgrenade.summarizer.db.tables.records.ArticleRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleDao extends DAOImpl<ArticleRecord, fi.redgrenade.summarizer.db.tables.pojos.Article, Long> {

    /**
     * Create a new ArticleDao without any configuration
     */
    public ArticleDao() {
        super(Article.ARTICLE, fi.redgrenade.summarizer.db.tables.pojos.Article.class);
    }

    /**
     * Create a new ArticleDao with an attached configuration
     */
    public ArticleDao(Configuration configuration) {
        super(Article.ARTICLE, fi.redgrenade.summarizer.db.tables.pojos.Article.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(fi.redgrenade.summarizer.db.tables.pojos.Article object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<fi.redgrenade.summarizer.db.tables.pojos.Article> fetchById(Long... values) {
        return fetch(Article.ARTICLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public fi.redgrenade.summarizer.db.tables.pojos.Article fetchOneById(Long value) {
        return fetchOne(Article.ARTICLE.ID, value);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<fi.redgrenade.summarizer.db.tables.pojos.Article> fetchByContent(String... values) {
        return fetch(Article.ARTICLE.CONTENT, values);
    }

    /**
     * Fetch records that have <code>header IN (values)</code>
     */
    public List<fi.redgrenade.summarizer.db.tables.pojos.Article> fetchByHeader(String... values) {
        return fetch(Article.ARTICLE.HEADER, values);
    }

    /**
     * Fetch records that have <code>summary IN (values)</code>
     */
    public List<fi.redgrenade.summarizer.db.tables.pojos.Article> fetchBySummary(String... values) {
        return fetch(Article.ARTICLE.SUMMARY, values);
    }

    /**
     * Fetch records that have <code>timestamp IN (values)</code>
     */
    public List<fi.redgrenade.summarizer.db.tables.pojos.Article> fetchByTimestamp(Timestamp... values) {
        return fetch(Article.ARTICLE.TIMESTAMP, values);
    }

    /**
     * Fetch records that have <code>rowCreateTime IN (values)</code>
     */
    public List<fi.redgrenade.summarizer.db.tables.pojos.Article> fetchByRowcreatetime(Timestamp... values) {
        return fetch(Article.ARTICLE.ROWCREATETIME, values);
    }
}
