/*
 * This file is generated by jOOQ.
*/
package fi.redgrenade.summarizer.db.tables.daos;


import fi.redgrenade.summarizer.db.tables.KeyWord;
import fi.redgrenade.summarizer.db.tables.records.KeyWordRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KeyWordDao extends DAOImpl<KeyWordRecord, fi.redgrenade.summarizer.db.tables.pojos.KeyWord, Long> {

    /**
     * Create a new KeyWordDao without any configuration
     */
    public KeyWordDao() {
        super(KeyWord.KEY_WORD, fi.redgrenade.summarizer.db.tables.pojos.KeyWord.class);
    }

    /**
     * Create a new KeyWordDao with an attached configuration
     */
    public KeyWordDao(Configuration configuration) {
        super(KeyWord.KEY_WORD, fi.redgrenade.summarizer.db.tables.pojos.KeyWord.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(fi.redgrenade.summarizer.db.tables.pojos.KeyWord object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<fi.redgrenade.summarizer.db.tables.pojos.KeyWord> fetchById(Long... values) {
        return fetch(KeyWord.KEY_WORD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public fi.redgrenade.summarizer.db.tables.pojos.KeyWord fetchOneById(Long value) {
        return fetchOne(KeyWord.KEY_WORD.ID, value);
    }

    /**
     * Fetch records that have <code>word IN (values)</code>
     */
    public List<fi.redgrenade.summarizer.db.tables.pojos.KeyWord> fetchByWord(String... values) {
        return fetch(KeyWord.KEY_WORD.WORD, values);
    }
}
